---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits
Our project will be done using a sequence of save and commits.
## First Verse 
<Put the first two verses of Jabberwocky by Lewis Carrol in this section>
"Beware the Jabberwock, my son!  
 The jaws that bite, the claws that catch!  
 Beware the Jubjub bird, and shun  
 The frumious Bandersnatch!"  
 He took his vorpal sword in hand:  
 Long time the manxome foe he sought --  
 So rested he by the Tumtum tree,  
 And stood awhile in thought.  
## Second Verse
<Put the first two verses of The Road Not Taken by Robert Frost here>
Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

Then took the other, as just as fair,  
And having perhaps the better claim,  
Because it was grassy and wanted wear;  
Though as for that the passing there  
Had worn them really about the same,  
## Third Verse
<Put the first two verses of The Walrus and The Carpenter
The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright--  
And this was odd, because it was  
The middle of the night.  

The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done--  
"It's very rude of him," she said,  
"To come and spoil the fun!"  
## Last Verse
<Put a short poem of your choice 8-20 lines,here>
To you I may be very small  
Or think I don't know much at all  
I've learned to grow up rather fast  
With so much future and not much past  

I'm just two years old but often sad  
I want so much to hug my dad  
He's protecting us from far away  
His life on the line everyday  

I watch my mom and see her cry  
I already know but still ask why?  
Her heart is hurting yet she tries to smile  
And we hold each other for a little while  

I'm still young yet very wise  
I have my fun but realize  
My soldier daddy is brave and strong  
I pray his deployment won't be long  

Source: http://www.familyfriendpoems.com/poem/soldier-daddy
